In [381]:
import numpy as np
import os

In [255]:
a = [1,2,3]
b = [1,3,5]
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [257]:
a = np.array([1,2,3])
b = np.array([1,3,5])
print(a*b)

[ 1  6 15]


In [259]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [261]:
b = np.array([[1,2,3],[1.1,2.2,3.3]])
print(b)

[[1.  2.  3. ]
 [1.1 2.2 3.3]]


In [263]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [265]:
# get Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [267]:
# Get type 
a.dtype

dtype('int64')

In [269]:
# Get size
a.itemsize

8

In [ ]:
a.size

In [271]:
# Get total size [ itemsize  * size]
a.nbytes

24

Accessing/Changing specific elements , row,columns

In [273]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype='int16')
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [275]:
# To get a specific element
a[1,5]

np.int16(13)

In [277]:
a[1,-4]

np.int16(11)

In [279]:
# Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

In [281]:
# Get specific column
a[:,2]

array([ 3, 10], dtype=int16)

In [ ]:
# Start:Step:Stop
a[0,1:6:2]

In [283]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [285]:
# 3-Diminsional
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a[0,1,1]

In [289]:
a[:,0,]

array([[1, 2],
       [5, 6]])

In [287]:
# Replace
a[:,1,:] = [[9,9],[8,8]]
print(a)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Different Types of Arrays

In [291]:
# All 0s
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [293]:
# All 1s
a = np.ones((4,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [295]:
a = np.full((3,3),5)
print(a)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# Full like 
np.full_like(a,4)
print(a)

In [299]:
# random decimal number
a = np.random.rand(3,2,6)
print(a)

[[[0.97250916 0.41641315 0.53194402 0.50364529 0.15901081 0.2826981 ]
  [0.49837779 0.49588182 0.47320346 0.42534354 0.648975   0.14493646]]

 [[0.39406999 0.39560129 0.19604152 0.31463007 0.42390017 0.07171451]
  [0.22588603 0.16260179 0.93874774 0.7017923  0.95951229 0.24635786]]

 [[0.56735292 0.86898099 0.57485953 0.91349895 0.42841727 0.86344427]
  [0.57451724 0.052366   0.70218889 0.54495758 0.22433312 0.97587472]]]


In [297]:
np.random.random_sample(a.shape)

array([[0.33329041, 0.55629043, 0.09582557],
       [0.48719283, 0.09785419, 0.53341519],
       [0.0339782 , 0.34213261, 0.8891539 ]])

In [301]:
#Integers
np.random.randint(1,10,(2,2))

array([[6, 6],
       [9, 8]], dtype=int32)

In [303]:
# Repeat an array 
b = np.array([[1,2,3]])
c = np.repeat(b,3,axis=0)
print(c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [305]:
b = np.array([[1,2,3]])
c = np.repeat(b,3,axis=1)
print(c)

[[1 1 1 2 2 2 3 3 3]]


In [307]:
output = np.full((5,5),1)
print(test)

z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [309]:
output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [311]:
# Copying Arrays 
a = np.array([1,2,3])
b = a #Contents in both the array changes
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [313]:
a = np.array([4,5,6])
b = a.copy() # Original Array remains the same 
b[0] = 1
print(b)
print(a)

[1 5 6]
[4 5 6]


In [315]:
a = np.array([1])
a1 = np.sin(a)
a2 = np.cos(a)
print(a1,a2)

[0.84147098] [0.54030231]


Linear Algebra

In [323]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [329]:
# Finding Determinant
c = np.eye(3)
print(c)

print(np.linalg.det(c))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [ ]:
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

Determinant
Trace
Singular Vector Decomposition
Eigen Values
Matrix Norm
Inverse

In [333]:
Statistics

In [339]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [353]:
print(np.min(stats))

1


In [355]:
print(np.max(stats))

6


In [357]:
print(np.sum(stats))

21


In [359]:
print(np.sum(stats,axis=0))

[5 7 9]


In [ ]:
Reorganizing Arrays

In [365]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [373]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [375]:
# Vertically Stacking Vectors
v1 = np.array([1,2])
v2 = np.array([3,4])

print(np.vstack([v1,v2]))



[[1 2]
 [3 4]]


In [377]:
# Horizontal Stack

h1 = np.array([1,2])
h2 = np.array([3,4])

print(np.hstack([v1,v2]))


[1 2 3 4]


In [ ]:
Miscellaneous

In [401]:
# Load data from file
filedata = np.genfromtxt(r'C:\Users\yoges\Downloads\data.txt',delimiter=',')
filedata = filedata.astype('int8')
print(filedata)

[[  1  13  21  11 -60  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33  -2  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 -25  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [405]:
# Boolean Masking & Advanced Indexing
filedata > 50

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [411]:
print(filedata[filedata>50]) # Indexed value

[75 75 55 78 76 88]


In [415]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])

[2 3 9]


In [417]:
np.any(filedata > 50,axis = 0)

array([False, False, False, False, False,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [421]:
(~((filedata > 50 ) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])