Numpy - Numerical Python

Advantages :
1. Allows several mathematical calculations
2. Faster operations

In [1]:
import numpy as np

In [2]:
# Creating 1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a.shape

(5,)

In [4]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
b.shape

(2, 4)

In [6]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Place Holders


In [7]:
# Create array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# Create array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Create an array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [10]:
# Create an Identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
# Create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.22167927 0.44921279 0.51034186 0.92376682]
 [0.4530004  0.08989337 0.62903406 0.45012119]
 [0.81400797 0.79843778 0.93835305 0.38818522]]


In [12]:
# Random integer values array
c = np.random.randint(10,100,(3,5))
print(c)

[[37 16 31 77 89]
 [19 30 22 70 39]
 [78 33 70 79 90]]


In [13]:
# Array of evenly spaced values - specifying required values
d = np.linspace(10,40,5)
print(d)

[10.  17.5 25.  32.5 40. ]


In [14]:
# Array of evenly spaced values - specifying the step
e = np.arange(10,40,5)
print(e)

[10 15 20 25 30 35]


In [15]:
# Convert a list to numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)



[10 20 30 40 50]


numpy.ndarray

In [16]:
tuple1 = (10,20,30,40,50)
np_array = np.asarray(tuple1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [17]:
c = np.random.randint(10,100,(4,4))
print(c)

[[79 87 79 62]
 [70 48 47 92]
 [37 80 82 13]
 [63 11 27 78]]


In [18]:
# array Dimension
c.shape

(4, 4)

In [19]:
# No.of dimension
c.ndim

2

In [20]:
# No.of elements
c.size

16

In [21]:
# Checking the data type of values in array
c.dtype

dtype('int32')

Mathematical Operations

In [22]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # Concatenate
print()

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a + b) # Element wise addition
print(a - b) # Element wise subtraction
print(a * b) # Element wise multiplication
print(a / b) # Element wise division

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Array Manipulation


In [23]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 8 7]
 [4 2 7]]
(2, 3)


In [24]:
# transpose
b = np.transpose(a)
print(b)
print(b.shape)

[[3 4]
 [8 2]
 [7 7]]
(3, 2)


In [25]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 5 7]
 [9 7 7]]
(2, 3)


In [26]:
# another method
b = a.T
print(b)
print(b.shape)


[[8 9]
 [5 7]
 [7 7]]
(3, 2)


In [27]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 1 3]
 [5 3 8]]
(2, 3)


In [28]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 1]
 [3 5]
 [3 8]]
(3, 2)
