Numpy - Numerical Python

Advantages :
1. Allows several mathematical calculations
2. Faster operations

In [2]:
import numpy as np

In [3]:
# Creating 1D array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
a.shape

(5,)

In [5]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
b.shape

(2, 4)

In [7]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Place Holders


In [8]:
# Create array of zeroes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# Create array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Create an array of particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [11]:
# Create an Identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# Create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.48128901 0.39898135 0.44180336 0.01422965]
 [0.55207229 0.51394575 0.94842075 0.02657045]
 [0.31274476 0.95756663 0.24181812 0.91143806]]


In [13]:
# Random integer values array
c = np.random.randint(10,100,(3,5))
print(c)

[[90 26 58 52 31]
 [72 48 49 33 95]
 [46 70 62 61 73]]


In [14]:
# random normal values array
d = np.random.normal(5,50,(3,3))
print(d)

[[ 44.13496724 -34.0708483   26.74006202]
 [ 39.6341168  -66.51604452 -97.974309  ]
 [ 74.52571175 -17.741893     3.75470618]]


In [15]:
# Array of evenly spaced values - specifying required values
d = np.linspace(10,40,5)
print(d)

[10.  17.5 25.  32.5 40. ]


In [16]:
# Array of evenly spaced values - specifying the step
e = np.arange(10,40,5)
print(e)

[10 15 20 25 30 35]


In [17]:
# Convert a list to numpy array
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)



[10 20 30 40 50]


numpy.ndarray

In [18]:
tuple1 = (10,20,30,40,50)
np_array = np.asarray(tuple1)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [19]:
c = np.random.randint(10,100,(4,4))
print(c)

[[28 19 16 82]
 [32 59 61 35]
 [52 34 94 44]
 [52 26 98 38]]


In [20]:
# array Dimension
c.shape

(4, 4)

In [21]:
# No.of dimension
c.ndim

2

In [22]:
# No.of elements
c.size

16

In [23]:
# Checking the data type of values in array
c.dtype

dtype('int64')

Mathematical Operations

In [24]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # Concatenate
print()

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
print(a + b) # Element wise addition
print(a - b) # Element wise subtraction
print(a * b) # Element wise multiplication
print(a / b) # Element wise division

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Array Manipulation


In [25]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 3 5]
 [6 6 6]]
(2, 3)


In [26]:
# transpose
b = np.transpose(a)
print(b)
print(b.shape)

[[2 6]
 [3 6]
 [5 6]]
(3, 2)


In [27]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 6 2]
 [5 0 6]]
(2, 3)


In [28]:
# another method
b = a.T
print(b)
print(b.shape)


[[9 5]
 [6 0]
 [2 6]]
(3, 2)


In [29]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 4 2]
 [0 4 4]]
(2, 3)


In [30]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[6 4]
 [2 0]
 [4 4]]
(3, 2)


In [31]:
# Square root
a = np.array([1,2,3,4,5])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]
